### ISSUE TITLE
Content not showing up online

### ISSUE THREAD

**Issue by saracase** [saracase/dsn1676-assignment-4#1]
So it seemed to be working fine during class but when I went to look at it again nothing showed up so I'm not sure what I'm missing.

 @thomasjbradley

**Comment by thomasjbradley** [comment]
Have you checked for error messages in “Console”?

**Comment by saracase** [comment]
It says there's a Uncaught SyntaxError: Unexpected token

**Comment by thomasjbradley** [comment]
What characters do you use for surrounding arrays?

**Comment by saracase** [comment]
Here's my code in javascirpt, probably easier if you just saw it

![screen shot 2015-02-11 at 9 47 31 am](https://cloud.githubusercontent.com/assets/6333956/6148928/0a6ae2ec-b1d3-11e4-8323-b6150c759178.png)

**Comment by thomasjbradley** [comment]
Thanks, but I can see it all on GitHub.

I know what the problem is, I'm just trying to prompt you to figure it out yourself :wink:.

Is `fruitBerries` an `array` or an `object`?

**Comment by saracase** [comment]
That makes sense, I don't know why but I thought you couldn't see the javascript code, it's early
An array I believe

**Comment by thomasjbradley** [comment]
Definitely an `array`, great.

So, then, the type of brackets surrounding your `fruitBerries` array, what should they be?

**Comment by saracase** [comment]
Square brackets, I knew my issue was going to be something really simple. Thanks!
